---
# tasks file for role_docker-test
# docker container run --name c1 -it --detach python

- name: Create single container
  hosts: localhost
  tasks:
  - community.docker.docker_container:
      name: c1
      image: python
      tty: true
      interactive: true