---
# vars file for role-create-loopbacks
interfaces:
  Loopback1337:
    description: "This is a loopback configured by ansible"
    ipv4addr: "192.168.124.100"
    subnet: "255.255.255.255"

  Loopback1338:
    description: "This is a loopback configured by ansible"
    ipv4addr: "192.168.124.101"
    subnet: "255.255.255.255"

  Loopback1339:
    description: "This is a loopback configured by ansible"
    ipv4addr: "192.168.124.102"
    subnet: "255.255.255.255"

  Loopback1340:
    description: "This is a loopback configured by ansible"
    ipv4addr: "192.168.124.103"
    subnet: "255.255.255.255"

  Loopback1341:
    description: "This is a loopback configured by ansible"
    ipv4addr: "192.168.124.104"
    subnet: "255.255.255.255"