version: "3.8"
services:
  vault-server:
    image: hashicorp/vault:latest
    container_name: vault-server
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - ./logs:/vault/logs
      - ./file:/vault/file
      - ./config:/vault/config
      - ./config/certs:/vault/certs
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
